id: freecodecamp
url: https://www.freecodecamp.org
category: Build
lenses:
  - education
  - free
quality: exceptional
title:
  en: freeCodeCamp
description:
  en: Learn programming through interactive lessons and projects.
