id: standard-ebooks
url: https://standardebooks.org
category: Knowledge
lenses:
- free
- open
- education
quality: solid
title:
  en: 'Standard Ebooks: Free and liberated ebooks'
description:
  en: Standard Ebooks offers free, high-quality, and liberated ebooks for book lovers,
    carefully produced for accessibility and enjoyment.
