id: candybox2
url: https://candybox2.github.io
category: Play
lenses:
  - indie
  - experimental
quality: exceptional
tags:
  popularity: low
  maturity: legacy
title:
  en: Candy Box 2
description:
  en: Deceptively simple incremental game that hides surprising depth.


