id: project-based-learning
url: https://github.com/practical-tutorials/project-based-learning
category: Build
lenses:
  - education
  - hands-on
quality: exceptional
tags:
  popularity: medium
  maturity: stable
title:
  en: Project Based Learning
description:
  en: Curated list of project ideas to learn programming by building.


