id: marginalrevolution
url: https://marginalrevolution.com
category: Knowledge
lenses:
  - economics
  - essays
quality: exceptional
tags:
  popularity: medium
  maturity: legacy
title:
  en: Marginal Revolution
description:
  en: Influential economics blog exploring incentives, markets, and policy.

