id: miljoenen
url: https://million.shortstory.io
category: Search
lenses:
  - creative
  - exploration
quality: niche
tags:
  popularity: low
  maturity: experimental
title:
  en: Million Short Story
description:
  en: Navigate a million interconnected short stories through links.


