id: our-world-in-data
url: https://ourworldindata.org
category: Knowledge
lenses:
  - data
  - research
quality: exceptional
title:
  en: Our World in Data
description:
  en: Research and data on global living conditions and challenges.
