id: buildyourownx
url: https://github.com/codecrafters-io/build-your-own-x
category: Build
lenses:
  - education
  - fundamentals
quality: exceptional
tags:
  popularity: medium
  maturity: stable
title:
  en: Build Your Own X
description:
  en: Step-by-step guides to building core technologies from scratch.


