id: teachyourselfcs
url: https://teachyourselfcs.com
category: Build
lenses:
  - education
  - fundamentals
quality: exceptional
tags:
  popularity: medium
  maturity: stable
title:
  en: Teach Yourself Computer Science
description:
  en: Curated guide to learning core computer science topics deeply.


