id: wiby
url: https://wiby.me
category: Search
lenses:
  - minimal
  - indie
quality: exceptional
tags:
  popularity: low
  maturity: stable
title:
  en: Wiby
description:
  en: Search engine for small, non-commercial, retro-style websites.


