id: standard-ebooks-org
url: https://standardebooks.org
category: Knowledge
lenses:
- free
- open
- indie
- education
quality: solid
title:
  en: Standard Ebooks
description:
  en: A collection of free and liberated ebooks, carefully produced for the true book
    lover.
