id: standard-ebooks
url: https://standardebooks.org
category: Knowledge
lenses:
- free
- education
- open
- indie
quality: solid
title:
  en: Standard Ebooks
description:
  en: A collection of free and liberated ebooks, carefully produced for book lovers.
