id: ncase-me
url: https://ncase.me
category: Knowledge
lenses:
- education
- curiosity
- indie
quality: exceptional
title:
  en: It's Nicky Case!
description:
  en: Nicky Case's website features interactive storytelling and educational games
    that explore complex topics in an engaging way.
