id: ncase-me
url: https://ncase.me
category: Knowledge
lenses:
- education
- curiosity
- storytelling
quality: exceptional
title:
  en: It's Nicky Case!
description:
  en: Nicky Case creates interactive stories and games that explore complex topics
    in an engaging way.
