id: the-pudding
url: https://pudding.cool
category: Explore
lenses:
  - data
  - storytelling
quality: exceptional
title:
  en: The Pudding
description:
  en: Visual essays explaining culture through data.
