id: littlealchemy2
url: https://littlealchemy2.com
category: Play
lenses:
  - creative
  - casual
quality: solid
tags:
  popularity: high
  maturity: stable
title:
  en: Little Alchemy 2
description:
  en: Combine elements to discover new items in a playful sandbox.


