id: excalidraw
url: https://excalidraw.com
category: Tools
lenses:
  - open
  - collaboration
quality: solid
title:
  en: Excalidraw
description:
  en: Simple, collaborative whiteboard with a hand-drawn feel.
