id: bookshop-org
url: https://bookshop.org
category: Buy
lenses:
  - ethical
quality: exceptional
title:
  en: Bookshop.org
description:
  en: Online bookstore supporting independent local bookshops.
