id: marginalia-search
url: https://search.marginalia.nu
category: Search
lenses:
  - indie
  - no-ads
quality: exceptional
tags:
  popularity: low
  maturity: experimental
title:
  en: Marginalia Search
description:
  en: Search engine focused on non-SEO, human-written content.


