id: library-of-babel
url: https://libraryofbabel.info
category: Explore
lenses:
  - art
  - philosophy
quality: exceptional
tags:
  popularity: low
  maturity: legacy
title:
  en: Library of Babel
description:
  en: Conceptual library containing every possible book of a fixed format.


